development:
  adapter: mysql2
  database: kings_chronos_dev
  username: root
  password: k1ngsl3y

test: &TEST
  adapter: mysql2
  database: kings_chronos_test
  username: root
  password: k1ngsl3y

production:
  adapter: mysql2
  host: sqlreadwrite.brightbox.net
  username: kings
  password: Xaib3ooGud8x
  database: kings_chronos_prod

cucumber: &CUCUMBER
  <<: *TEST
culerity:
  <<: *CUCUMBER